# Generated by Django 5.1.6 on 2025-08-17 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sowing',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sowing',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sowings', to='crops.municipality'),
        ),
        migrations.AddField(
            model_name='sowing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowings', to='crops.product'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='sowing',
            index=models.Index(fields=['sowing_date'], name='crops_sowin_sowing__1acecf_idx'),
        ),
        migrations.AddIndex(
            model_name='sowing',
            index=models.Index(fields=['status'], name='crops_sowin_status_08f4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='sowing',
            index=models.Index(fields=['municipality'], name='crops_sowin_municip_e8803a_idx'),
        ),
    ]
