# Generated by Django 5.1.6 on 2025-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sowing',
            name='harvest_date',
        ),
        migrations.AddField(
            model_name='sowing',
            name='unit',
            field=models.CharField(choices=[('ha', 'Hectáreas'), ('ton', 'Toneladas'), ('m2', 'Metros cuadrados'), ('plantas', 'Número de plantas')], default='ha', help_text='Unidad de medida', max_length=20),
        ),
    ]
