# Generated by Django 5.1.6 on 2025-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_remove_sowing_harvest_date_sowing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
