# Generated by Django 5.1.6 on 2025-08-19 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_municipality_latitude_municipality_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropParametrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('hum_min', models.FloatField(blank=True, null=True)),
                ('hum_max', models.FloatField(blank=True, null=True)),
                ('rain_min', models.FloatField(blank=True, null=True)),
                ('rain_max', models.FloatField(blank=True, null=True)),
                ('wind_max', models.FloatField(blank=True, null=True)),
                ('w_temp', models.FloatField(default=0.4)),
                ('w_hum', models.FloatField(default=0.3)),
                ('w_rain', models.FloatField(default=0.2)),
                ('w_wind', models.FloatField(default=0.1)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='crops.product')),
            ],
        ),
    ]
