# Generated by Django 5.1.6 on 2025-08-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_cropparametrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('min_rain', models.FloatField(blank=True, null=True)),
                ('max_rain', models.FloatField(blank=True, null=True)),
                ('min_humidity', models.FloatField(blank=True, null=True)),
                ('max_humidity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CropParametrer',
        ),
    ]
