# Generated by Django 5.1.6 on 2025-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_product_max_humidity_product_max_rain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowing',
            name='unit',
            field=models.CharField(choices=[('ha', 'Hectáreas'), ('A', 'Fanegada')], help_text='Unidad de medida', max_length=20),
        ),
    ]
