# Generated by Django 5.2.5 on 2025-08-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0008_alter_sowing_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_per_fanegada",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_per_hectare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cycle_days",
            field=models.IntegerField(
                blank=True, help_text="Días aproximados para cosecha", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="max_altitude",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="min_altitude",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sowing",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="sowing",
            name="estimated_harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
