# Generated by Django 5.2.5 on 2025-08-21 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0009_product_cost_per_fanegada_product_cost_per_hectare_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=100)),
                ("date", models.DateTimeField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("k", "kilo"), ("t", "tonelada"), ("a", "arroba")],
                        help_text="Unidad de medida",
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="crops.product",
                    ),
                ),
            ],
        ),
    ]
