# Generated by Django 5.1.6 on 2025-08-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0009_product_cost_per_fanegada_product_cost_per_hectare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowing',
            name='area',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sowing',
            name='area_unit',
            field=models.CharField(choices=[('hectarea', 'Hectárea'), ('fanegada', 'Fanegada')], default='hectarea', max_length=10),
        ),
        migrations.AddField(
            model_name='sowing',
            name='expected_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='unit',
            field=models.CharField(choices=[('hectarea', 'Hectárea'), ('fanegada', 'Fanegada')], help_text='Unidad de medida', max_length=20),
        ),
    ]
