# Generated by Django 5.1.6 on 2025-08-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_prices'),
        ('crops', '0010_sowing_area_sowing_area_unit_and_more'),
    ]

    operations = [
    ]
