# Generated by Django 5.1.6 on 2025-08-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0012_prices_user_alter_prices_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_per_fanegada',
        ),
        migrations.AddField(
            model_name='product',
            name='yield_per_hectare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.category'),
        ),
    ]
