# Generated by Django 5.1.6 on 2025-08-16 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sowing',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sowing',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sowings', to='cultivos.municipality'),
        ),
        migrations.AddField(
            model_name='sowing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sowings', to='cultivos.product'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='sowing',
            index=models.Index(fields=['sowing_date'], name='cultivos_so_sowing__285d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='sowing',
            index=models.Index(fields=['status'], name='cultivos_so_status_dd5e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='sowing',
            index=models.Index(fields=['municipality'], name='cultivos_so_municip_3b72cd_idx'),
        ),
    ]
